// <auto-generated />
using System;
using CfoAgent.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CfoAgent.Api.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260715141904_InitialFinanceSchema")]
    partial class InitialFinanceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CfoAgent.Api.Models.Finance.BudgetTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssumptionReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ProfitTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasFilter("\"Month\" IS NULL");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasFilter("\"Month\" IS NOT NULL");

                    b.ToTable("BudgetTargets", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetTargets_Month_Valid", "\"Month\" IS NULL OR (\"Month\" >= 1 AND \"Month\" <= 12)");

                            t.HasCheckConstraint("CK_BudgetTargets_ProfitTarget_NonNegative", "\"ProfitTarget\" IS NULL OR CAST(\"ProfitTarget\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_BudgetTargets_SalesTarget_NonNegative", "CAST(\"SalesTarget\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_BudgetTargets_Year_Positive", "\"Year\" > 0");
                        });
                });

            modelBuilder.Entity("CfoAgent.Api.Models.Finance.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CfoAgent.Api.Models.Finance.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleDate");

                    b.ToTable("Sales", t =>
                        {
                            t.HasCheckConstraint("CK_Sales_Discount_DoesNotExceedGross", "CAST(\"DiscountAmount\" AS REAL) <= \"Quantity\" * CAST(\"UnitPrice\" AS REAL)");

                            t.HasCheckConstraint("CK_Sales_Discount_NonNegative", "CAST(\"DiscountAmount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_Sales_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Sales_UnitCost_NonNegative", "CAST(\"UnitCost\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_Sales_UnitPrice_NonNegative", "CAST(\"UnitPrice\" AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("CfoAgent.Api.Models.Finance.Sale", b =>
                {
                    b.HasOne("CfoAgent.Api.Models.Finance.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CfoAgent.Api.Models.Finance.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
