// <auto-generated />
using System;
using CfoAgent.FinanceMcpServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CfoAgent.FinanceMcpServer.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CfoAgent.FinanceMcpServer.Models.Finance.BudgetTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssumptionReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ProfitTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SalesTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasFilter("\"Month\" IS NULL");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasFilter("\"Month\" IS NOT NULL");

                    b.ToTable("BudgetTargets", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetTargets_Month_Valid", "\"Month\" IS NULL OR (\"Month\" >= 1 AND \"Month\" <= 12)");

                            t.HasCheckConstraint("CK_BudgetTargets_ProfitTarget_NonNegative", "\"ProfitTarget\" IS NULL OR \"ProfitTarget\" >= 0");

                            t.HasCheckConstraint("CK_BudgetTargets_SalesTarget_NonNegative", "\"SalesTarget\" >= 0");

                            t.HasCheckConstraint("CK_BudgetTargets_Year_Positive", "\"Year\" > 0");
                        });
                });

            modelBuilder.Entity("CfoAgent.FinanceMcpServer.Models.Finance.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CfoAgent.FinanceMcpServer.Models.Finance.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleDate");

                    b.ToTable("Sales", t =>
                        {
                            t.HasCheckConstraint("CK_Sales_Discount_DoesNotExceedGross", "\"DiscountAmount\" <= \"Quantity\" * \"UnitPrice\"");

                            t.HasCheckConstraint("CK_Sales_Discount_NonNegative", "\"DiscountAmount\" >= 0");

                            t.HasCheckConstraint("CK_Sales_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Sales_UnitCost_NonNegative", "\"UnitCost\" >= 0");

                            t.HasCheckConstraint("CK_Sales_UnitPrice_NonNegative", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("CfoAgent.FinanceMcpServer.Models.Finance.Sale", b =>
                {
                    b.HasOne("CfoAgent.FinanceMcpServer.Models.Finance.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CfoAgent.FinanceMcpServer.Models.Finance.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
